version: '3.3'

services:

  centos:
    image: iganarix/base-centos-7
    container_name: update-jenkins_centos
    tty: true

  ubuntu:
    image: iganarix/base-ubuntu-16.04
    container_name: update-jenkins_ubuntu
    tty: true